@MyBGList_HostAddress = http://localhost:40080

GET {{MyBGList_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{MyBGList_HostAddress}}/BoardGames?filterQuery=diplomacy
Accept: application/json

###
