@MyBGList_HostAddress = http://localhost:40080

GET {{MyBGList_HostAddress}}/swagger/v1/swagger.json
Accept: application/json

###

GET {{MyBGList_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{MyBGList_HostAddress}}/BoardGames?pageSize=10&sortOrder=desc&sortColumn=name
Accept: application/json

###
